First iteration
imbalaancing/go_final_project pull request #1
Opened 2024-06-20 12:06 UTC by imbalaancing

2024-06-20 20:18 UTC, dirtymew requested changes
Привет Никита

хорошая работа - хочется отметить лейаут проекта, документацию и логирование

есть что поправить  см комментарии но в целом OK

вопрос - задания со звездочкой будешь делать?

2024-06-20 20:18 UTC, dirtymew commented on Dockerfile
> +FROM golang:latest AS builder
лучше зафиксировать тут же версию что и в go mod go 1.22.3

2024-06-20 20:18 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=1 go build -o /my_app ./cmd/server/main.go
CGO_ENABLED=1 - лучше в ENV

2024-06-20 20:18 UTC, dirtymew commented on Dockerfile
> +ENV HTTP_PORT=7540
лучше единообразно переменные окружения назыать - TODO_PORT

да и по заданию вроде так требовалось и приложение тоже ждет другую переменную окружения

2024-06-20 20:18 UTC, dirtymew commented on Dockerfile
> +EXPOSE 7540
а есть TODO_PORT другой?

2024-06-20 20:18 UTC, dirtymew commented on cmd/server/main.go
> +	log.Printf("Запуск сервера на порту %s...\n", port)
отлично при запуске понятно что приложение работает

2024-06-20 20:18 UTC, dirtymew commented on README.md
> +Этот проект представляет собой веб-приложение, написанное на Go и JavaScript. Он использует SQLite для хранения данных и предоставляет API для работы с задачами.
хорошо что написал документацию

2024-06-20 20:18 UTC, dirtymew commented on cmd/server/main.go
> +	defer database.Close()
отлично что не забыл закрыть соединение

2024-06-20 20:18 UTC, dirtymew commented on internal/api/handlers.go
> +		_, err = time.Parse("20060102", t.Date)
20060102 лучше в константу DATE_FORMAT использовать

много где используется

2024-06-20 20:18 UTC, dirtymew commented on internal/api/handlers.go
> +	rows, err := database.Query(`SELECT * FROM scheduler ORDER BY date ASC LIMIT 50`)
лимит то же в константу

2024-06-20 20:43 UTC, imbalaancing commented on internal/api/handlers.go
> +	rows, err := database.Query(`SELECT * FROM scheduler ORDER BY date ASC LIMIT 50`)
Привет, спасибо за замечания, поправлю все.  Что касается заданий со звездочкой, то боюсь, что не успею реализовать все, потому что уже пробовал и достаточно надолго встревал на одном из шагов, поэтому решил пропустить ту же аутентификацию. В общем, что было посильно, то и реализовал)

2024-06-22 13:42 UTC, dirtymew requested changes
Привет Никита

предлагаю провести  рефакторинг кода хендлеров

дал рекомендации

2024-06-22 13:42 UTC, dirtymew commented on Dockerfile
> +EXPOSE 7540
@imbalaancing тут не поправил - лучше переместить в низ и там присвоить значение переменной окружения

2024-06-22 13:42 UTC, dirtymew commented on internal/api/handlers.go
> +	rows, err := database.Query(`SELECT * FROM scheduler ORDER BY date ASC LIMIT ?`, TaskLimit)
тут лучше не использовать * а явно в селекте поля указать

2024-06-22 13:42 UTC, dirtymew commented on internal/api/handlers.go
> +	if t.Title == "" {
лучше разнести на разные пакеты/функции
- проверки отдельно 
- за запросы должен уровень хранилища отвечать а не хендлер

в итоге код очень перегружен

в твоей архитектура давай запросы в пакет db унесем
проверки и структуру Task в Tasks

в хедлерах нужно оставить только получение данных из реквеста( их проверну - не путать с валидацией - это все в пакете task) и  респонс с http хедерами

мб поможет https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10

2024-06-30 14:43 UTC, dirtymew requested changes
Привет Никита

дал комментарии что еще стоит улучшить

2024-06-30 14:43 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.22.3 AS builder
кажется хотел сделать [multistage](https://docs.docker.com/build/building/multi-stage/)
и не доделал

надо доделать иди убрать AS builder

2024-06-30 14:43 UTC, dirtymew commented on internal/task/task.go
> +func ValidateTask(t *Task) error {
лучше сделать методом структуры Task

func (t *Task) ValidateTask() error { ....

2024-06-30 14:43 UTC, dirtymew commented on internal/task/task.go
> +func NextDate(now time.Time, date string, repeat string) (string, error) {
это к задаче не очень относится - лучше вынести в пакет date(nextdate)

2024-06-30 14:43 UTC, dirtymew commented on internal/db/db.go
> +func InsertTask(db *sql.DB, t *task.Task) error {
не очень хорошо передавать все время db *sql.DB,

лучше сделать структуру, констуктор и все функции сделать ее методами- например такую
```
type Storage struct {
	db *sql.DB
}

func NewTaskStorage(db *sql.DB)  *Storage {
   return &Storage{db: db}
}


func(s *Storage)  Insert(t *task.Task) error { 

....
```

2024-06-30 14:43 UTC, dirtymew commented on internal/db/db.go
> +func InitDB() (*sql.DB, error) {
лучше так  func InitDB(dbFileName string)

2024-07-01 15:20 UTC, dirtymew requested changes
Привет Никита

есть вопросы по докерфайлу и главное тесты падают - нужно чтобы проходили

2024-07-01 15:20 UTC, dirtymew commented on Dockerfile
> +COPY . .
ну тут кажется что одной команды COPY . . с верху будет достаточно

о на скопирует и go.mod go.sum
и код 
и web /app/web - у тебя же WORKDIR /app определена ...

2024-07-01 15:20 UTC, dirtymew commented on Dockerfile
> +EXPOSE 7540
а если TODO_PORT -будет другой - экспозится все равно будет 7540 - стоит поправить

2024-07-02 08:29 UTC, dirtymew approved these changes
Привет Никита

теперь все отлично - задание выполнено

Поздравляю

2024-07-02 08:29 UTC, dirtymew commented on cmd/server/main.go
> +	http.Handle("/web/", http.StripPrefix("/web/", fs))
тут поему ошибка и фронт не запуститься как надо  

мб `http.Handle("/", fs)` ? @imbalaancing

2024-07-02 09:55 UTC, imbalaancing commented on cmd/server/main.go
> +	http.Handle("/web/", http.StripPrefix("/web/", fs))
Спасибо за все. Ты главный ревьюер, который на протяжении всего обучения проверил, наверное, процентов 70% моих работ. Спасибо за опыт, спасибо за терпение!

2024-07-02 09:55 UTC, merged